apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "deadman.fullname" . }}
  labels:
    {{- include "deadman.labels" . | nindent 4 }}
data:
  config.yml: |
    {{ .Values.deadman.config | nindent 4 }}
