apiVersion: v1
kind: Service
metadata:
  name: {{ include "deadman.fullname" . }}
  labels:
    {{- include "deadman.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.deadman.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "deadman.selectorLabels" . | nindent 4 }}
